apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service-app
  labels:
    app: book-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : book-service-app
  template:
    metadata:
      labels:
        app: book-service-app
    spec:
      containers:
      - name: book-service-app
        image: kunalpi/book-service
        imagePullPolicy: Always
        ports:
          - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name:  book-service-svc
spec:
  selector:
    app:  book-service-app
  ports:
  - port:  80
    targetPort:  8080